[package]
name = "rust_image_share"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "wgpu",
]

[dependencies]
serde_json = "1.0.99"
local-ip-address = "0.5.3"